CREATE TRIGGER atualizarQuantidade
ON ITENS_VENDA
AFTER INSERT AS
BEGIN
	DECLARE @ESTOQUE INT, @IDFK_PRODUTO INT

	SELECT @IDFK_PRODUTO = IDFK_PRODUTOS, @ESTOQUE = QUANTIDADE FROM INSERTED
	UPDATE PRODUTOS SET ESTOQUE = ESTOQUE - @ESTOQUE WHERE COD_PROD = @IDFK_PRODUTO
END

INSERT INTO ITENS_VENDA
(
	QUANTIDADE, SUB_TOTAL, IDFK_VENDA, IDFK_PRODUTOS
)
VALUES
(
	1, 150, 5, 1
)
