CREATE TRIGGER exibirNomeFantasia
ON PRODUTOS
AFTER INSERT AS 
BEGIN
	DECLARE @IDFK_DISTRIBUIDOR INT
	SELECT @IDFK_DISTRIBUIDOR = IDFK_DISTRIBUIDOR FROM INSERTED
	SELECT NOME_FANTASIA, RAZAO_SOCIAL FROM DISTRIBUIDORES WHERE COD_DIST = @IDFK_DISTRIBUIDOR
END

INSERT INTO PRODUTOS 
(
	COD_PROD, PRECO_VENDA, DESCRICAO, DATA_VALIDADE, PRECO_CUSTO, ESTOQUE, IDFK_DISTRIBUIDOR
)
VALUES
(
	'454545', 'Mercadinho Zé', 'Mercadinho do Zé LTDA', '00028922', 'zezinho@hotmail.com', '5'
)
