CREATE TRIGGER exibirNomeEmail
ON VENDAS
AFTER INSERT AS 
BEGIN 
	DECLARE @IDFK_CLIENTE INT 
	SELECT @IDFK_CLIENTE = IDFK_CLIENTE FROM INSERTED
	IF (@IDFK_CLIENTE = '' OR @IDFK_CLIENTE = null)
	BEGIN
		PRINT ('ERRO!!!')
	END
	ELSE
	BEGIN
		SELECT NOME, EMAIL FROM CLIENTES WHERE COD_CLI = @IDFK_CLIENTE
	END
END

INSERT INTO VENDAS
(
	COD_VENDA, DATA_HORA, TOTAL, IDFK_CLIENTE
)
VALUES
(
	'013', '020-10-17', '115.25', '2'
)
INSERT INTO VENDAS
(
	COD_VENDA, DATA_HORA, TOTAL, IDFK_CLIENTE
)
VALUES
(
	'014', '2020-05-05', '15.00', '3'
)
