CREATE PROCEDURE inserirDistribuidor
	@COD_DIST INT,
	@NOME_FANTASIA VARCHAR(100),
	@RAZAO_SOCIAL VARCHAR(100),
	@TELEFONE VARCHAR(100),
	@EMAIL VARCHAR(100)

AS
BEGIN

DECLARE @RESULTADO VARCHAR;

IF (@NOME_FANTASIA <> @RAZAO_SOCIAL)

BEGIN
INSERT INTO DISTRIBUIDORES (COD_DIST, NOME_FANTASIA, RAZAO_SOCIAL, TELEFONE, EMAIL) 
VALUES (@COD_DIST, @NOME_FANTASIA, @RAZAO_SOCIAL, @TELEFONE, @EMAIL);

END

SET @NOME_FANTASIA = @RESULTADO;

SET @RAZAO_SOCIAL = @RESULTADO; 

SELECT @RESULTADO

END

EXEC inserirDistribuidor '454545', 'Mercadinho Zé', 'Mercadinho do Zé LTDA', '00028922', 'zezinho@hotmail.com'
