CREATE PROCEDURE inserirVenda
	@COD_VENDA INT,
	@DATA_HORA DATETIME ,
	@TOTAL FLOAT NOT NULL

AS
BEGIN

DECLARE @RESULTADO INT;

IF (@TOTAL>2000 OR @TOTAL<1000 AND @TOTAL>0)

BEGIN 
INSERT INTO VENDAS (COD_VENDA, DATA_HORA, TOTAL) VALUES (@COD_VENDA, @DATA_HORA, @TOTAL);

END

SET @TOTAL = @RESULTADO;

SELECT @RESULTADO

END

EXEC inserirVenda '15', '2020-10-14', '115.00'

